config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

	resources :users

	get '/secret-page', to: 'users#secret'


	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'

	delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@email = params[:session][:email]
		mon_user = User.find_by(email: @email.downcase)

		if mon_user && mon_user.authenticate(params[:session][:password])
			log_in(mon_user)

			redirect_to user_path(mon_user.id)
		else
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_path
	end

end

# params[:email]
# params[:password]

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@users_tab = User.all
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    mon_user = User.new(email: params[:email] , password: params[:password])
    if mon_user.save
        log_in(mon_user)
  	  	redirect_to '/'
      end
  end

  def show
  	@id = params[:id]
  	@user = User.find(@id)

    puts "-"*50
    print "\tES-TU ES-TU LOGGER :"
    puts logged_in?
    puts "-"*50
  end

  def edit
    @id = params[:id]
    @user = User.find(@id)
  	@email = @user.email
  end

  def update
    @user = User.find(params[:id])
    
    user_param = params.require(:user).permit(:email, :password)
    @user.update(user_param)

  	redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end


  def secret

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
	    session[:user_id] = user.id
	    puts "*"*60
	    print "ID DU GARS DE LA SESSION: ", session[:user_id], "\n"
	end


	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	  <header>
	      <ul class="nav nav-pills nav-fill">
	        <li class="nav-item"> <a class="nav-link active" href="<%= root_path%>" >Accueil</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="/login" >Connexion</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="<%= users_path %>" >Inscription</a> </li>
	        <% if logged_in? %>
	        <li class="nav-item" >
				<%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %>
			</li>
	        <% else %>
	        	<li class="nav-item" >
	        		 <%= link_to "Log in", "/login", class: 'nav-link'%> 
	        	</li>
	    	<% end %>
		</ul>
	</header>
<!-- users = possède GET & POST -->

	<div class="center jumbotron">
	  <h1>Bienvenue !</h1>
	  <h3> Et si on inscrivait des étudiants ? 🎓 </h3>
	  <%= link_to "New Student", users_path, class: "btn btn-lg btn-primary" %>

	  <% if logged_in? %>
	   <%= link_to "GO Page Secrete", "/secret-page", class: "btn btn-lg btn-warning" %>
	  <% else %>
	   <%= link_to "GO Page Secrete", "/login", class: "btn btn-lg btn-warning" %>
	  <% end %>

	</div>

	<h2>TOUS LES EMAILS:</h2>
	<ul>
		<% @users_tab.each do |user| %>
		<li> <a href="<%= user_path(user.id) %>"> <%= user.email %> </a> </li>
		<% end %>
	</ul>

</body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>EDIT USER</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	<header>
	      <ul class="nav nav-pills nav-fill">
	        <li class="nav-item"> <a class="nav-link" href="<%= root_path%>" >Accueil</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="/login" >Connexion</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="<%= users_path %>" >Inscription</a> </li>
	        <% if logged_in? %>
	        <li class="nav-item" >
				<%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %>
			</li>
	        <% else %>
	        	<li class="nav-item" >
	        		 <%= link_to "Log in", "/login", class: 'nav-link'%> 
	        	</li>
	    	<% end %>
		</ul>
	</header>



    <div class="center jumbotron">
    	<h1>Editons l'User <%= @id+ ' ' +@email%> </h1>
	
    	<%= form_for @user do |f| %>
	    	<div class="form-group">
				<label>Entrer un nouvel Email</label>
	    		<%= f.text_field :email, class: 'form-control' %>
			</div>

			<div class="form-group">
				<label>Entrer votre Password OU votre NOUVEAU password</label>
	    		<%= f.text_field :password, class: 'form-control' %>				
			</div>

			<div>
				<button type="submit" class="btn btn-primary">Modifier l'User</button>
			</div>
    	<% end %>

	</div>

</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CREATE</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	 <header>
	      <ul class="nav nav-pills nav-fill">
	        <li class="nav-item"> <a class="nav-link" href="<%= root_path%>" >Accueil</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="/login" >Connexion</a> </li>
	        <li class="nav-item"> <a class="nav-link active" href="<%= users_path %>" >Inscription</a> </li>
	        <% if logged_in? %>
	        <li class="nav-item" >
				<%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %>
			</li>
	        <% else %>
	        	<li class="nav-item" >
	        		 <%= link_to "Log in", "/login", class: 'nav-link'%> 
	        	</li>
	    	<% end %>
		</ul>
	</header>
<!-- users = possède GET & POST -->

	<div class="center jumbotron">
	  <h1>Inscris toi: </h1>
	  <br><br><br>

	  <form method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<div class="form-group">
			    <label>Email</label>
			    <input name="email" type="text" class="form-control" placeholder="Enter your email">
		    <small class="form-text text-muted">On gardera cet email pour nous ;)</small>
			</div>

		  <div class="form-group">
		    <label>Password</label>
		    <input name="password" type="password" class="form-control" placeholder="Enter your password">
		  </div>

		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>


	</div>





</body>
</html>

app/views/users/secret.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>


	<header>
	      <ul class="nav nav-pills nav-fill">
	        <li class="nav-item"> <a class="nav-link" href="<%= root_path%>" >Accueil</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="/login" >Connexion</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="<%= users_path %>" >Inscription</a> </li>
	        <% if logged_in? %>
	        <li class="nav-item" >
				<%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %>
			</li>
	        <% else %>
	        	<li class="nav-item" >
	        		 <%= link_to "Log in", "/login", class: 'nav-link'%> 
	        	</li>
	    	<% end %>
		</ul>
	</header>
<!-- users = possède GET & POST -->

	<div class="center jumbotron">
		<h1>Des infos en pagailles: </h1> <br>
		
		<% if logged_in? %>
			<h2>Info à  voir seulement si tu es connecter: </h2>
			<p><strong> 42 </strong></p>
		<% else %>
			<h2>Info pour les gens non connecter :): </h2>
			<p><strong> Bien le bonjour </strong></p>
		<% end %>


		<br>
		<%= link_to "Bleu", "/secret-page", class: "btn btn-lg btn-primary" %>
		<%= link_to "Jaune", "/secret-page", class: "btn btn-lg btn-warning" %>
	</div>

	




</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	<header>
	      <ul class="nav nav-pills nav-fill">
	        <li class="nav-item"> <a class="nav-link" href="<%= root_path%>" >Accueil</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="/login" >Connexion</a> </li>
	        <li class="nav-item"> <a class="nav-link" href="<%= users_path %>" >Inscription</a> </li>
	        <% if logged_in? %>
	        <li class="nav-item" >
				<%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %>
			</li>
	        <% else %>
	        	<li class="nav-item" >
	        		 <%= link_to "Log in", "/login", class: 'nav-link'%> 
	        	</li>
	    	<% end %>
		</ul>
	</header>
<!-- users = possède GET & POST -->

	<div class="center jumbotron">
		<h1>User N°<%= @id %> </h1>
		<p>
			<strong>Email: </strong>
			<%= @user.email %> <br><br>

			<% if @current_user != nil && @current_user.id == @user.id %>
				<%= link_to "Editer ce mail", edit_user_path(params[:id]), class: "btn btn-primary" %>
				<a href= <%= user_path(params[:id]) %> class="btn btn-danger" data-method="delete">DELETE</a>
			<% end %>
		</p>
	</div>




</body>
</html>